name: Release CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: Installer les dépendances
        run: flutter pub get

      - name: Vérifier les tests
        run: flutter test

      - name: Rendre release.sh exécutable
        run: chmod +x ./release.sh

      - name: Lancer la release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./release.sh release-it
